version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 15
  target-branch: master
  ignore:
  - dependency-name: io.undertow:undertow-servlet
    versions:
    - "> 2.0.30.Final, < 3"
  - dependency-name: ro.isdc.wro4j:wro4j-maven-plugin
    versions:
    - "> 1.8.0, < 2"
  - dependency-name: ro.isdc.wro4j:wro4j-maven-plugin
    versions:
    - ">= 1.9.a, < 1.10"
  - dependency-name: org.eclipse.jetty:jetty-util
    versions:
    - 11.0.0
  - dependency-name: org.eclipse.jetty:jetty-annotations
    versions:
    - 11.0.0
  - dependency-name: org.eclipse.jetty:jetty-webapp
    versions:
    - 11.0.0
  - dependency-name: org.eclipse.jetty:jetty-jndi
    versions:
    - 11.0.0
  - dependency-name: org.eclipse.jetty:jetty-plus
    versions:
    - 11.0.0
  - dependency-name: org.eclipse.jetty:jetty-servlet
    versions:
    - 11.0.0
  - dependency-name: org.eclipse.jetty:jetty-server
    versions:
    - 11.0.0