version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 15
  target-branch: master
  ignore:
  - dependency-name: io.undertow:undertow-servlet
    versions:
    - "> 2.0.30.Final, < 3"
  - dependency-name: ro.isdc.wro4j:wro4j-maven-plugin
    versions:
    - "> 1.8.0, < 2"
  - dependency-name: ro.isdc.wro4j:wro4j-maven-plugin
    versions:
    - ">= 1.9.a, < 1.10"
  - dependency-name: org.eclipse.jetty:jetty-util
    versions:
    - 11.0.0
  - dependency-name: org.eclipse.jetty:jetty-annotations
    versions:
    - 11.0.0
  - dependency-name: org.eclipse.jetty:jetty-webapp
    versions:
    - 11.0.0
  - dependency-name: org.eclipse.jetty:jetty-jndi
    versions:
    - 11.0.0
  - dependency-name: org.eclipse.jetty:jetty-plus
    versions:
    - 11.0.0
  - dependency-name: org.eclipse.jetty:jetty-servlet
    versions:
    - 11.0.0
  - dependency-name: org.eclipse.jetty:jetty-server
    versions:
    - 11.0.0
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 15
  target-branch: "3.1"
  ignore:
  - dependency-name: com.sun.xml.bind:jaxb-ri
    versions:
    - ">= 3.a, < 4"
  - dependency-name: com.sun.xml.messaging.saaj:saaj-impl
    versions:
    - ">= 2.a, < 3"
  - dependency-name: com.sun.xml.ws:jaxws-ri
    versions:
    - ">= 3.a, < 4"
  - dependency-name: jakarta.activation:jakarta.activation-api
    versions:
    - ">= 2.a, < 3"
  - dependency-name: jakarta.el:jakarta.el-api
    versions:
    - ">= 4.a, < 5"
  - dependency-name: jakarta.enterprise:cdi-tck-api
    versions:
    - ">= 3.a, < 4"
  - dependency-name: jakarta.faces:jakarta.faces-api
    versions:
    - ">= 3.a, < 4"
  - dependency-name: jakarta.servlet.jsp:jakarta.servlet.jsp-api
    versions:
    - ">= 3.a, < 4"
  - dependency-name: jakarta.websocket:jakarta.websocket-api
    versions:
    - ">= 2.a, < 3"
  - dependency-name: jakarta.xml.ws:jakarta.xml.ws-api
    versions:
    - ">= 3.a, < 4"
  - dependency-name: org.apache.tomcat.embed:tomcat-embed-core
    versions:
    - ">= 10.a, < 11"
  - dependency-name: org.apache.tomcat.embed:tomcat-embed-jasper
    versions:
    - ">= 10.a, < 11"
  - dependency-name: org.eclipse.jetty:jetty-annotations
    versions:
    - ">= 10.a, < 11"
  - dependency-name: org.eclipse.jetty:jetty-annotations
    versions:
    - ">= 11.a, < 12"
  - dependency-name: org.eclipse.jetty:jetty-deploy
    versions:
    - ">= 10.a, < 11"
  - dependency-name: org.eclipse.jetty:jetty-deploy
    versions:
    - ">= 11.a, < 12"
  - dependency-name: org.eclipse.jetty:jetty-jndi
    versions:
    - ">= 10.a, < 11"
  - dependency-name: org.eclipse.jetty:jetty-jndi
    versions:
    - ">= 11.a, < 12"
  - dependency-name: org.eclipse.jetty:jetty-plus
    versions:
    - ">= 10.a, < 11"
  - dependency-name: org.eclipse.jetty:jetty-plus
    versions:
    - ">= 11.a, < 12"
  - dependency-name: org.eclipse.jetty:jetty-server
    versions:
    - ">= 10.a, < 11"
  - dependency-name: org.eclipse.jetty:jetty-server
    versions:
    - ">= 11.a, < 12"
  - dependency-name: org.eclipse.jetty:jetty-servlet
    versions:
    - ">= 10.a, < 11"
  - dependency-name: org.eclipse.jetty:jetty-servlet
    versions:
    - ">= 11.a, < 12"
  - dependency-name: org.eclipse.jetty:jetty-util
    versions:
    - ">= 10.a, < 11"
  - dependency-name: org.eclipse.jetty:jetty-util
    versions:
    - ">= 11.a, < 12"
  - dependency-name: org.eclipse.jetty:jetty-webapp
    versions:
    - ">= 10.a, < 11"
  - dependency-name: org.eclipse.jetty:jetty-webapp
    versions:
    - ">= 11.a, < 12"
  - dependency-name: org.glassfish:jakarta.el
    versions:
    - ">= 4.a, < 5"
  - dependency-name: org.glassfish:jakarta.faces
    versions:
    - ">= 3.a, < 4"
  - dependency-name: org.jboss.weld:weld-api
    versions:
    - ">= 4.a, < 5"
  - dependency-name: org.jboss.weld:weld-api-bom
    versions:
    - ">= 4.a, < 5"
  - dependency-name: org.jboss.weld:weld-api-parent
    versions:
    - ">= 4.a, < 5"
  - dependency-name: org.testng:testng
    versions:
    - ">= 7.a, < 8"
  - dependency-name: ro.isdc.wro4j:wro4j-maven-plugin
    versions:
    - "> 1.8.0, < 2"
  - dependency-name: ro.isdc.wro4j:wro4j-maven-plugin
    versions:
    - ">= 1.9.a, < 1.10"
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 15
  target-branch: "4.0"
  ignore:
  - dependency-name: io.undertow:undertow-servlet
    versions:
    - "> 2.0.30.Final, < 3"
  - dependency-name: ro.isdc.wro4j:wro4j-maven-plugin
    versions:
    - "> 1.8.0, < 2"
  - dependency-name: ro.isdc.wro4j:wro4j-maven-plugin
    versions:
    - ">= 1.9.a, < 1.10"
  - dependency-name: org.eclipse.jetty:jetty-util
    versions:
    - 11.0.0
  - dependency-name: org.eclipse.jetty:jetty-annotations
    versions:
    - 11.0.0
  - dependency-name: org.eclipse.jetty:jetty-webapp
    versions:
    - 11.0.0
  - dependency-name: org.eclipse.jetty:jetty-jndi
    versions:
    - 11.0.0
  - dependency-name: org.eclipse.jetty:jetty-plus
    versions:
    - 11.0.0
  - dependency-name: org.eclipse.jetty:jetty-servlet
    versions:
    - 11.0.0
  - dependency-name: org.eclipse.jetty:jetty-server
    versions:
    - 11.0.0
